sudo: required
language: generic

services:
  - docker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

before_install:
  - docker build -t isdckft/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true isdckft/react-test npm test

after_success:
  - docker build -t isdckft/multi-client ./client
  - docker build -t isdckft/multi-nginx ./nginx
  - docker build -t isdckft/multi-server ./server
  - docker build -t isdckft/multi-worker ./worker

  # Take those images and push them to docker hub
  - docker push isdckft/multi-client
  - docker push isdckft/multi-nginx
  - docker push isdckft/multi-server
  - docker push isdckft/multi-worker
